<a href="https://colab.research.google.com/github/cut-lip/ML_Practice/blob/main/NumpyPrac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#### We can  use the `np.array()` method to construct and initialize a NumPy array with the given values. We may print the array with the `print()` method.

In [3]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


####The `np.array()` method works for 2-D arrays as well, by including inner sets of square brackets.

In [4]:
two_dimensional_array = np.array([ [6, 5], [11, 7], [4, 8] ])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


####The methods `np.zeros` and `np.ones` may be used to fill a NumPy array with zeros or ones. The 'shape' parameter must be specified as the dimensions of the array (single number for length if one dimensional.

In [5]:
zero_array = np.zeros(5)
print(zero_array)

[0. 0. 0. 0. 0.]


####Using `np.arange` (note: a-range), a NumPy array may be initialized from a given range (exclusive) as follows:

In [6]:
integer_sequence = np.arange(7, 17)
print(integer_sequence)

[ 7  8  9 10 11 12 13 14 15 16]


####An array may be populated with random numbers using various functions, including `np.random.randint`. This function generates an array of the given `size` with random integers generated between the `low` and `high`, exclusive.

In [6]:
random_integer_array = np.random.randint(low = 25, high = 101, size = 12)
print(random_integer_array)

[88 57 91 60 92 75 58 70 30 91 91 91]


####For an array containing random double values between 0.0 and 1.0, `np.random.random` may be used with a given size.

In [4]:
random_floats_between_0_and_1 = np.random.random([10])
print(random_floats_between_0_and_1)

[0.35154047 0.19502464 0.02811673 0.95652745 0.93168071 0.06631174
 0.38727885 0.69341327 0.50092401 0.73936536]


In NumPy, we have the ability to expand the dimensions of a given matrix in order to make at compatible for matrix arithmetic with another matrix. This feat can be accomplished through the automatic NumPy feature called broadcasting, which will expand a given operand to the required dimensions for the given matrix calculation. In the example below, the constant 2.0 is broadcasted to have the same dimensions as the matrix from the previous example.

In [4]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.09281251 2.10981598 2.60948858 2.70391663 2.89111536 2.10869051
 2.65549045 2.22619938 2.74011631 2.87494634]


Broadcasting may also be done in the context of multiplication operations on matrices, as show below where the constant 3.0 is broadcasted.

In [8]:
random_integer_array_times_3 = random_integer_array * 3
print(random_integer_array_times_3)

[264 171 273 180 276 225 174 210  90 273 273 273]


##Okay. Lets go about creating a linear dataset using NumPy functionality. This dataset consists of single-Dimensional labeled data.

In [2]:
# Create a NumPy array containing the range of integers from 6 to 20, inclusive
feature = np.arange(6, 21)
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
# Create a NumPy array containing labels for the feature array
# Base label format on this expression: label = (3) feature + 4
# Broadcasting allows us to use constands with our matrix arithmetic
label = (feature * 3) + 4
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


#Lets now practice adding some noise to the dataset, in order to simulate a real dataset more closely. For this simulation, we will add random floating-point values between -2 and +2 to our data.

In [5]:
noise = np.random.random( [15] * 4) - 2
print(noise)

[ 1.10719502 -1.21092298  1.50958659 -1.80561711 -0.93957542  1.14727974
  0.24723305 -0.89262266  1.80627415  0.60062643  1.86546585  1.82316688
 -0.0651133  -0.69663044 -1.61894418]


In [6]:
label = label + noise
print(label)

[23.10719502 23.78907702 29.50958659 29.19438289 33.06042458 38.14727974
 40.24723305 42.10737734 47.80627415 49.60062643 53.86546585 56.82316688
 57.9348867  60.30336956 62.38105582]
